# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fn_sign_double <- function(x) {
    .Call('_BayesMVPv2_fn_sign_double', PACKAGE = 'BayesMVPv2', x)
}

fn_sign_log_vec <- function(x) {
    .Call('_BayesMVPv2_fn_sign_log_vec', PACKAGE = 'BayesMVPv2', x)
}

fn_sign_log_mat <- function(x) {
    .Call('_BayesMVPv2_fn_sign_log_mat', PACKAGE = 'BayesMVPv2', x)
}

fastpow2_1 <- function(p) {
    .Call('_BayesMVPv2_fastpow2_1', PACKAGE = 'BayesMVPv2', p)
}

fastpow2_1_double <- function(p) {
    .Call('_BayesMVPv2_fastpow2_1_double', PACKAGE = 'BayesMVPv2', p)
}

fast_exp_0_Eigen <- function(x) {
    .Call('_BayesMVPv2_fast_exp_0_Eigen', PACKAGE = 'BayesMVPv2', x)
}

fast_exp_0_Eigen_rowvec <- function(x) {
    .Call('_BayesMVPv2_fast_exp_0_Eigen_rowvec', PACKAGE = 'BayesMVPv2', x)
}

fast_log_0_Eigen <- function(x) {
    .Call('_BayesMVPv2_fast_log_0_Eigen', PACKAGE = 'BayesMVPv2', x)
}

fast_log_0_Eigen_rowvec <- function(x) {
    .Call('_BayesMVPv2_fast_log_0_Eigen_rowvec', PACKAGE = 'BayesMVPv2', x)
}

fast_exp_0_Eigen_mat <- function(x) {
    .Call('_BayesMVPv2_fast_exp_0_Eigen_mat', PACKAGE = 'BayesMVPv2', x)
}

fast_exp_0_Eigen_mat_RM <- function(x) {
    .Call('_BayesMVPv2_fast_exp_0_Eigen_mat_RM', PACKAGE = 'BayesMVPv2', x)
}

fast_log_0_Eigen_mat <- function(x) {
    .Call('_BayesMVPv2_fast_log_0_Eigen_mat', PACKAGE = 'BayesMVPv2', x)
}

fast_log_0_Eigen_mat_RM <- function(x) {
    .Call('_BayesMVPv2_fast_log_0_Eigen_mat_RM', PACKAGE = 'BayesMVPv2', x)
}

fast_exp_1 <- function(x) {
    .Call('_BayesMVPv2_fast_exp_1', PACKAGE = 'BayesMVPv2', x)
}

fast_exp_1_double <- function(x) {
    .Call('_BayesMVPv2_fast_exp_1_double', PACKAGE = 'BayesMVPv2', x)
}

fast_exp_1_Eigen_float <- function(x) {
    .Call('_BayesMVPv2_fast_exp_1_Eigen_float', PACKAGE = 'BayesMVPv2', x)
}

fast_exp_1_Eigen_mat_float <- function(x) {
    .Call('_BayesMVPv2_fast_exp_1_Eigen_mat_float', PACKAGE = 'BayesMVPv2', x)
}

fast_exp_1_Eigen <- function(x) {
    .Call('_BayesMVPv2_fast_exp_1_Eigen', PACKAGE = 'BayesMVPv2', x)
}

fast_exp_1_Eigen_colvec <- function(x) {
    .Call('_BayesMVPv2_fast_exp_1_Eigen_colvec', PACKAGE = 'BayesMVPv2', x)
}

fast_exp_1_Eigen_mat <- function(x) {
    .Call('_BayesMVPv2_fast_exp_1_Eigen_mat', PACKAGE = 'BayesMVPv2', x)
}

fast_exp_1_Eigen_mat_RM <- function(x) {
    .Call('_BayesMVPv2_fast_exp_1_Eigen_mat_RM', PACKAGE = 'BayesMVPv2', x)
}

fast_exp_1_Eigen_v2 <- function(x) {
    .Call('_BayesMVPv2_fast_exp_1_Eigen_v2', PACKAGE = 'BayesMVPv2', x)
}

fast_exp_3 <- function(p) {
    .Call('_BayesMVPv2_fast_exp_3', PACKAGE = 'BayesMVPv2', p)
}

exp_stan <- function(x) {
    .Call('_BayesMVPv2_exp_stan', PACKAGE = 'BayesMVPv2', x)
}

log_stan <- function(x) {
    .Call('_BayesMVPv2_log_stan', PACKAGE = 'BayesMVPv2', x)
}

inv_logit_stan <- function(x) {
    .Call('_BayesMVPv2_inv_logit_stan', PACKAGE = 'BayesMVPv2', x)
}

tanh_stan <- function(x) {
    .Call('_BayesMVPv2_tanh_stan', PACKAGE = 'BayesMVPv2', x)
}

erfc_stan <- function(x) {
    .Call('_BayesMVPv2_erfc_stan', PACKAGE = 'BayesMVPv2', x)
}

Phi_stan <- function(x) {
    .Call('_BayesMVPv2_Phi_stan', PACKAGE = 'BayesMVPv2', x)
}

Phi_using_erfc_stan <- function(x) {
    .Call('_BayesMVPv2_Phi_using_erfc_stan', PACKAGE = 'BayesMVPv2', x)
}

inv_Phi_stan <- function(x) {
    .Call('_BayesMVPv2_inv_Phi_stan', PACKAGE = 'BayesMVPv2', x)
}

exp_Eigen <- function(x) {
    .Call('_BayesMVPv2_exp_Eigen', PACKAGE = 'BayesMVPv2', x)
}

log_Eigen <- function(x) {
    .Call('_BayesMVPv2_log_Eigen', PACKAGE = 'BayesMVPv2', x)
}

Rcpp_mult_mat_by_col_vec <- function(mat, colvec) {
    .Call('_BayesMVPv2_Rcpp_mult_mat_by_col_vec', PACKAGE = 'BayesMVPv2', mat, colvec)
}

Rcpp_mult_mat_by_col_vec_float <- function(mat, colvec) {
    .Call('_BayesMVPv2_Rcpp_mult_mat_by_col_vec_float', PACKAGE = 'BayesMVPv2', mat, colvec)
}

Rcpp_mult_mat_by_mat <- function(mat_1, mat_2) {
    .Call('_BayesMVPv2_Rcpp_mult_mat_by_mat', PACKAGE = 'BayesMVPv2', mat_1, mat_2)
}

Rcpp_det <- function(mat) {
    .Call('_BayesMVPv2_Rcpp_det', PACKAGE = 'BayesMVPv2', mat)
}

Rcpp_log_det <- function(mat) {
    .Call('_BayesMVPv2_Rcpp_log_det', PACKAGE = 'BayesMVPv2', mat)
}

Rcpp_solve <- function(mat) {
    .Call('_BayesMVPv2_Rcpp_solve', PACKAGE = 'BayesMVPv2', mat)
}

Rcpp_Chol <- function(mat) {
    .Call('_BayesMVPv2_Rcpp_Chol', PACKAGE = 'BayesMVPv2', mat)
}

fn_calculate_cutpoints <- function(log_diffs, first_cutpoint, K) {
    .Call('_BayesMVPv2_fn_calculate_cutpoints', PACKAGE = 'BayesMVPv2', log_diffs, first_cutpoint, K)
}

vec_of_mats_test <- function(n_rows, n_cols, n_mats) {
    .Call('_BayesMVPv2_vec_of_mats_test', PACKAGE = 'BayesMVPv2', n_rows, n_cols, n_mats)
}

vec_of_mats_test_int <- function(n_rows, n_cols, n_mats) {
    .Call('_BayesMVPv2_vec_of_mats_test_int', PACKAGE = 'BayesMVPv2', n_rows, n_cols, n_mats)
}

vec_of_mats_test_bool <- function(n_rows, n_cols, n_mats) {
    .Call('_BayesMVPv2_vec_of_mats_test_bool', PACKAGE = 'BayesMVPv2', n_rows, n_cols, n_mats)
}

vec_of_mats_test_int_Ones <- function(n_rows, n_cols, n_mats) {
    .Call('_BayesMVPv2_vec_of_mats_test_int_Ones', PACKAGE = 'BayesMVPv2', n_rows, n_cols, n_mats)
}

vec_of_mats_test_RM <- function(n_rows, n_cols, n_mats) {
    .Call('_BayesMVPv2_vec_of_mats_test_RM', PACKAGE = 'BayesMVPv2', n_rows, n_cols, n_mats)
}

fn_convert_3d_array_of_corrs_to_Eigen_vec_RM <- function(input_array, n_rows, n_arrays) {
    .Call('_BayesMVPv2_fn_convert_3d_array_of_corrs_to_Eigen_vec_RM', PACKAGE = 'BayesMVPv2', input_array, n_rows, n_arrays)
}

std_vec_to_Eigen_vec <- function(std_vec) {
    .Call('_BayesMVPv2_std_vec_to_Eigen_vec', PACKAGE = 'BayesMVPv2', std_vec)
}

Eigen_vec_to_std_vec <- function(Eigen_vec) {
    .Call('_BayesMVPv2_Eigen_vec_to_std_vec', PACKAGE = 'BayesMVPv2', Eigen_vec)
}

fn_convert_unconstrained_to_corrs_double_RM <- function(Omega_unconstrained) {
    .Call('_BayesMVPv2_fn_convert_unconstrained_to_corrs_double_RM', PACKAGE = 'BayesMVPv2', Omega_unconstrained)
}

phi_sq_sum <- function(phi) {
    .Call('_BayesMVPv2_phi_sq_sum', PACKAGE = 'BayesMVPv2', phi)
}

phi_sq_x_M_inv_sum <- function(phi, M_inv) {
    .Call('_BayesMVPv2_phi_sq_x_M_inv_sum', PACKAGE = 'BayesMVPv2', phi, M_inv)
}

fn_log_1m_Phi_double <- function(x) {
    .Call('_BayesMVPv2_fn_log_1m_Phi_double', PACKAGE = 'BayesMVPv2', x)
}

fn_log_Phi_double <- function(x) {
    .Call('_BayesMVPv2_fn_log_Phi_double', PACKAGE = 'BayesMVPv2', x)
}

fn_log_Phi_double_vec <- function(x) {
    .Call('_BayesMVPv2_fn_log_Phi_double_vec', PACKAGE = 'BayesMVPv2', x)
}

commutation_dot <- function(n, m, x, transpose) {
    .Call('_BayesMVPv2_commutation_dot', PACKAGE = 'BayesMVPv2', n, m, x, transpose)
}

get_commutation <- function(n, m) {
    .Call('_BayesMVPv2_get_commutation', PACKAGE = 'BayesMVPv2', n, m)
}

elimination_matrix <- function(n) {
    .Call('_BayesMVPv2_elimination_matrix', PACKAGE = 'BayesMVPv2', n)
}

duplication_matrix <- function(n) {
    .Call('_BayesMVPv2_duplication_matrix', PACKAGE = 'BayesMVPv2', n)
}

notExp2_double <- function(x) {
    .Call('_BayesMVPv2_notExp2_double', PACKAGE = 'BayesMVPv2', x)
}

notExp2_vec <- function(x) {
    .Call('_BayesMVPv2_notExp2_vec', PACKAGE = 'BayesMVPv2', x)
}

notExp2_deriv_double <- function(x) {
    .Call('_BayesMVPv2_notExp2_deriv_double', PACKAGE = 'BayesMVPv2', x)
}

notExp2_deriv_vec <- function(x) {
    .Call('_BayesMVPv2_notExp2_deriv_vec', PACKAGE = 'BayesMVPv2', x)
}

notLog2_double <- function(x) {
    .Call('_BayesMVPv2_notLog2_double', PACKAGE = 'BayesMVPv2', x)
}

notLog2_vec <- function(x) {
    .Call('_BayesMVPv2_notLog2_vec', PACKAGE = 'BayesMVPv2', x)
}

fast_exp_double_wo_checks_Eigen <- function(x) {
    .Call('_BayesMVPv2_fast_exp_double_wo_checks_Eigen', PACKAGE = 'BayesMVPv2', x)
}

fast_exp_double_wo_checks_Eigen_mat <- function(x) {
    .Call('_BayesMVPv2_fast_exp_double_wo_checks_Eigen_mat', PACKAGE = 'BayesMVPv2', x)
}

fast_exp_approx_double_wo_checks <- function(p) {
    .Call('_BayesMVPv2_fast_exp_approx_double_wo_checks', PACKAGE = 'BayesMVPv2', p)
}

fast_exp_approx_double_wo_checks_Eigen <- function(x) {
    .Call('_BayesMVPv2_fast_exp_approx_double_wo_checks_Eigen', PACKAGE = 'BayesMVPv2', x)
}

fast_exp_approx_double_wo_checks_Eigen_mat <- function(x) {
    .Call('_BayesMVPv2_fast_exp_approx_double_wo_checks_Eigen_mat', PACKAGE = 'BayesMVPv2', x)
}

fast_log_approx_double_wo_checks_Eigen <- function(x) {
    .Call('_BayesMVPv2_fast_log_approx_double_wo_checks_Eigen', PACKAGE = 'BayesMVPv2', x)
}

fast_log_approx_double_wo_checks_Eigen_mat <- function(x) {
    .Call('_BayesMVPv2_fast_log_approx_double_wo_checks_Eigen_mat', PACKAGE = 'BayesMVPv2', x)
}

fn_ld_exp_bitshift_1 <- function(b) {
    .Call('_BayesMVPv2_fn_ld_exp_bitshift_1', PACKAGE = 'BayesMVPv2', b)
}

fn_ld_exp_bitshift_2 <- function(a, b) {
    .Call('_BayesMVPv2_fn_ld_exp_bitshift_2', PACKAGE = 'BayesMVPv2', a, b)
}

fast_tanh_approx_Eigen <- function(x) {
    .Call('_BayesMVPv2_fast_tanh_approx_Eigen', PACKAGE = 'BayesMVPv2', x)
}

Phi_using_erfc_Eigen <- function(x) {
    .Call('_BayesMVPv2_Phi_using_erfc_Eigen', PACKAGE = 'BayesMVPv2', x)
}

inv_logit_1_Eigen <- function(x) {
    .Call('_BayesMVPv2_inv_logit_1_Eigen', PACKAGE = 'BayesMVPv2', x)
}

fast_inv_logit_1_Eigen <- function(x) {
    .Call('_BayesMVPv2_fast_inv_logit_1_Eigen', PACKAGE = 'BayesMVPv2', x)
}

Phi_approx_Eigen <- function(x) {
    .Call('_BayesMVPv2_Phi_approx_Eigen', PACKAGE = 'BayesMVPv2', x)
}

fast_Phi_approx_1_Eigen <- function(x) {
    .Call('_BayesMVPv2_fast_Phi_approx_1_Eigen', PACKAGE = 'BayesMVPv2', x)
}

qnorm_rcpp_Eigen <- function(p) {
    .Call('_BayesMVPv2_qnorm_rcpp_Eigen', PACKAGE = 'BayesMVPv2', p)
}

qnorm_w_fast_log_rcpp_Eigen <- function(p) {
    .Call('_BayesMVPv2_qnorm_w_fast_log_rcpp_Eigen', PACKAGE = 'BayesMVPv2', p)
}

Phi_approx_fast_Eigen <- function(x) {
    .Call('_BayesMVPv2_Phi_approx_fast_Eigen', PACKAGE = 'BayesMVPv2', x)
}

inv_Phi_approx_fast_Eigen <- function(x) {
    .Call('_BayesMVPv2_inv_Phi_approx_fast_Eigen', PACKAGE = 'BayesMVPv2', x)
}

fn_lp_and_grad_latent_trait_MD_and_AD <- function(theta_main, theta_us, y, X, other_args) {
    .Call('_BayesMVPv2_fn_lp_and_grad_latent_trait_MD_and_AD', PACKAGE = 'BayesMVPv2', theta_main, theta_us, y, X, other_args)
}

fn_lp_and_grad_MVP_using_Chol_Spinkney_MD_and_AD <- function(theta_main, theta_us, y, X, other_args) {
    .Call('_BayesMVPv2_fn_lp_and_grad_MVP_using_Chol_Spinkney_MD_and_AD', PACKAGE = 'BayesMVPv2', theta_main, theta_us, y, X, other_args)
}

fn_mult_scalar_x_vec_using_log_sign_arrays_double <- function(x, y) {
    .Call('_BayesMVPv2_fn_mult_scalar_x_vec_using_log_sign_arrays_double', PACKAGE = 'BayesMVPv2', x, y)
}

fn_mult_vec_x_vec_using_log_sign_arrays_double <- function(x, y) {
    .Call('_BayesMVPv2_fn_mult_vec_x_vec_using_log_sign_arrays_double', PACKAGE = 'BayesMVPv2', x, y)
}

fn_mult_mat_x_mat_using_log_sign_arrays_double <- function(x, y) {
    .Call('_BayesMVPv2_fn_mult_mat_x_mat_using_log_sign_arrays_double', PACKAGE = 'BayesMVPv2', x, y)
}

fn_log_abs_sum_exp_vectorised_double <- function(x_signs, y_signs, log_x, log_y) {
    .Call('_BayesMVPv2_fn_log_abs_sum_exp_vectorised_double', PACKAGE = 'BayesMVPv2', x_signs, y_signs, log_x, log_y)
}

fn_log_abs_sum_exp_mult_mat_by_col_vec_double <- function(signs_A_mat, signs_b_vec, log_abs_A_mat, log_abs_b_vec) {
    .Call('_BayesMVPv2_fn_log_abs_sum_exp_mult_mat_by_col_vec_double', PACKAGE = 'BayesMVPv2', signs_A_mat, signs_b_vec, log_abs_A_mat, log_abs_b_vec)
}

draw_mean_zero_norm_Rcpp <- function(draws_vec, SD_vec) {
    .Call('_BayesMVPv2_draw_mean_zero_norm_Rcpp', PACKAGE = 'BayesMVPv2', draws_vec, SD_vec)
}

draw_mean_zero_norm_using_Zigg_Rcpp <- function(draws_vec, SD_vec) {
    .Call('_BayesMVPv2_draw_mean_zero_norm_using_Zigg_Rcpp', PACKAGE = 'BayesMVPv2', draws_vec, SD_vec)
}

Rcpp_fn_sampling_single_iter_burnin <- function(Model_type, theta_main_array, theta_us_array, y, X, other_args, L, eps, log_posterior, M_inv_us_array, M_dense_main, M_inv_dense_main, M_inv_dense_main_chol) {
    .Call('_BayesMVPv2_Rcpp_fn_sampling_single_iter_burnin', PACKAGE = 'BayesMVPv2', Model_type, theta_main_array, theta_us_array, y, X, other_args, L, eps, log_posterior, M_inv_us_array, M_dense_main, M_inv_dense_main, M_inv_dense_main_chol)
}

Rcpp_fn_post_burnin_HMC_post_adaptation_phase_float_big_version <- function(Model_type, theta_main_array, theta_us_array, y, X, other_args, tau_jittered, n_iter, n_chain_for_loading_bar, tau, eps, log_posterior, M_inv_us_array, M_dense_main, M_inv_dense_main, M_inv_dense_main_chol) {
    .Call('_BayesMVPv2_Rcpp_fn_post_burnin_HMC_post_adaptation_phase_float_big_version', PACKAGE = 'BayesMVPv2', Model_type, theta_main_array, theta_us_array, y, X, other_args, tau_jittered, n_iter, n_chain_for_loading_bar, tau, eps, log_posterior, M_inv_us_array, M_dense_main, M_inv_dense_main, M_inv_dense_main_chol)
}

